### ISSUE TITLE
Didn't provide the entire code?

### ISSUE THREAD

**Issue by 945716994** [OpenRL-Lab/TiZero#1]
I didn't see the section on how to train the model.

**Comment by huangshiyu13** [comment]
Our code will be released in OpenRL: https://github.com/OpenRL-Lab/openrl
But the release time is still uncertain.

If you want to receive a training code before release, you are welcome to cooperate with us by sending an email to huangshiyu@4paradigm.com

**Comment by 945716994** [comment]
> Our code will be released in OpenRL: https://github.com/OpenRL-Lab/openrl But the release time is still uncertain.
> 
> If you want to receive a training code before release, you are welcome to cooperate with us by sending an email to [huangshiyu@4paradigm.com](mailto:huangshiyu@4paradigm.com)

I just sent an email.
